// Generated by gencpp from file semi_truck/Teensy_Sensors.msg
// DO NOT EDIT!


#ifndef SEMI_TRUCK_MESSAGE_TEENSY_SENSORS_H
#define SEMI_TRUCK_MESSAGE_TEENSY_SENSORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace semi_truck
{
template <class ContainerAllocator>
struct Teensy_Sensors_
{
  typedef Teensy_Sensors_<ContainerAllocator> Type;

  Teensy_Sensors_()
    : wheel_speed(0)
    , imu_angle(0)
    , right_TOF(0)
    , left_TOF(0)
    , rear_TOF(0)
    , drive_mode_1(0)
    , drive_mode_2(0)  {
    }
  Teensy_Sensors_(const ContainerAllocator& _alloc)
    : wheel_speed(0)
    , imu_angle(0)
    , right_TOF(0)
    , left_TOF(0)
    , rear_TOF(0)
    , drive_mode_1(0)
    , drive_mode_2(0)  {
  (void)_alloc;
    }



   typedef int16_t _wheel_speed_type;
  _wheel_speed_type wheel_speed;

   typedef int16_t _imu_angle_type;
  _imu_angle_type imu_angle;

   typedef int16_t _right_TOF_type;
  _right_TOF_type right_TOF;

   typedef int16_t _left_TOF_type;
  _left_TOF_type left_TOF;

   typedef int16_t _rear_TOF_type;
  _rear_TOF_type rear_TOF;

   typedef int16_t _drive_mode_1_type;
  _drive_mode_1_type drive_mode_1;

   typedef int16_t _drive_mode_2_type;
  _drive_mode_2_type drive_mode_2;





  typedef boost::shared_ptr< ::semi_truck::Teensy_Sensors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::semi_truck::Teensy_Sensors_<ContainerAllocator> const> ConstPtr;

}; // struct Teensy_Sensors_

typedef ::semi_truck::Teensy_Sensors_<std::allocator<void> > Teensy_Sensors;

typedef boost::shared_ptr< ::semi_truck::Teensy_Sensors > Teensy_SensorsPtr;
typedef boost::shared_ptr< ::semi_truck::Teensy_Sensors const> Teensy_SensorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::semi_truck::Teensy_Sensors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::semi_truck::Teensy_Sensors_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace semi_truck

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'semi_truck': ['/home/nate/git/daimtronics/semi_catkin_ws/src/semi_truck/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::semi_truck::Teensy_Sensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::semi_truck::Teensy_Sensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::semi_truck::Teensy_Sensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::semi_truck::Teensy_Sensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::semi_truck::Teensy_Sensors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::semi_truck::Teensy_Sensors_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::semi_truck::Teensy_Sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9623202c8fe03b3ac3d8a917b632561e";
  }

  static const char* value(const ::semi_truck::Teensy_Sensors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9623202c8fe03b3aULL;
  static const uint64_t static_value2 = 0xc3d8a917b632561eULL;
};

template<class ContainerAllocator>
struct DataType< ::semi_truck::Teensy_Sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "semi_truck/Teensy_Sensors";
  }

  static const char* value(const ::semi_truck::Teensy_Sensors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::semi_truck::Teensy_Sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 wheel_speed\n\
int16 imu_angle\n\
int16 right_TOF\n\
int16 left_TOF\n\
int16 rear_TOF\n\
int16 drive_mode_1\n\
int16 drive_mode_2\n\
";
  }

  static const char* value(const ::semi_truck::Teensy_Sensors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::semi_truck::Teensy_Sensors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wheel_speed);
      stream.next(m.imu_angle);
      stream.next(m.right_TOF);
      stream.next(m.left_TOF);
      stream.next(m.rear_TOF);
      stream.next(m.drive_mode_1);
      stream.next(m.drive_mode_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Teensy_Sensors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::semi_truck::Teensy_Sensors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::semi_truck::Teensy_Sensors_<ContainerAllocator>& v)
  {
    s << indent << "wheel_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.wheel_speed);
    s << indent << "imu_angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.imu_angle);
    s << indent << "right_TOF: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right_TOF);
    s << indent << "left_TOF: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left_TOF);
    s << indent << "rear_TOF: ";
    Printer<int16_t>::stream(s, indent + "  ", v.rear_TOF);
    s << indent << "drive_mode_1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.drive_mode_1);
    s << indent << "drive_mode_2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.drive_mode_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEMI_TRUCK_MESSAGE_TEENSY_SENSORS_H
